version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres:13.1-alpine
    restart: always
    networks:
      - aplication_production
    environment:
      POSTGRES_PASSWORD: password

  client:
    container_name: client
    restart: always
    networks:
      - aplication_production
    build:
      context: .
      dockerfile: ./client/Dockerfile
      cache_from:
        - node:14
    ports:
      - 8080:8080
    volumes:
      - ./client:/client
      - node_modules:./client/node_module

  api:
    container_name: api
    restart: always
    networks:
      - aplication_production
    build:
      context: .
      dockerfile: ./api/Dockerfile
      cache_from:
        - ruby:2.5.7
    ports:
      - 3000:3000
    volumes:
      - ./api/:/api
    links:
      - db
    depends_on:
      - db

networks:
  aplication_production:
    driver: bridge
