version: "3.8"
services:
  db:
    container_name: db
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - aplication_production
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  client:
    container_name: client
    restart: always
    networks:
      - aplication_production
    build:
      context: .
      dockerfile: ./client/Dockerfile
      cache_from:
        - node:14
    ports:
      - 8080:8080
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules

  api:
    container_name: api
    restart: always
    networks:
      - aplication_production
    build:
      context: .
      dockerfile: ./api/Dockerfile
      cache_from:
        - ruby:2.5.7
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ./api/:/api
    links:
      - db
    depends_on:
      - db

networks:
  aplication_production:
    driver: bridge

volumes:
  node_modules:
