name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  deployment:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.5.7
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rails test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 9f9ec2b085093cb9f44faa57d682351d69e2d89621a2a8ecf3d7d34cb998ea26
      with:
        coverageCommand: yarn coverage
      
#   build:
#     runs-on: ubuntu-latest
#     services:
#       db:
#         image: postgres
#         ports: ['5432:5432']
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Ruby 2.6
#       uses: actions/setup-ruby@v1
#       with:
#         ruby-version: 2.6
#     - name: Build with Rake
#       env:
#         PGHOST: 127.0.0.1
#         PGUSER: postgres
#       run: |
#         sudo apt-get -yqq install libpq-dev
#         gem install bundler
#         bundle install --jobs 4 --retry 3
#         bundle exec rake db:create
#         bundle exec rake db:migrate
