name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  deployment:
    branches: [ master ]

jobs:        
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Set up Node lts-alpine
      uses: actions/setup-node@v1
      with:
        node-version: lts-alpine

    - name: Build Docker
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
      run: |
        sudo docker-compose up --build

