name: CI

on:
  push:
  pull_request:
    branches: [ master ]
  deployment:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build api containers
        run: docker-compose up --build -d
        
  api_test:
    needs: [ build ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
      
    - name: Build api container
      run:  |
        docker-compose up --detach --build db api
        
    - name: Run api tests
      run: |
        docker-compose run api bundle exec rake test


    - name: API Sonar coverage scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: api
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_API }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  client_test:
    needs: [ build ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2

    - name: Build client container
      run: |
        docker-compose up --detach --build client

    - name: Run client tests
      run: |
        docker-compose run client yarn run test:unit

    - name: Client Sonar coverage scan
      uses: SonarSource/sonarcloud-github-action@v1.4
      with:
        projectBaseDir: client
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  api_deploy:
    needs: [ api_test ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_SECRET}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file api/Dockerfile --tag fabianaribas/trabalho-individual-2020-1:api_latest

      - name: Docker Push
        run: docker push fabianaribas/trabalho-individual-2020-1:api_latest
      
#   client_deploy:
#     needs: [ client_test ]
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./client
#     steps:
#       - uses: actions/checkout@v2
#       - name: docker login
#         env:
#           DOCKER_USER: ${{secrets.DOCKER_USER}}
#           DOCKER_PASSWORD: ${{secrets.DOCKER_SECRET}}
#         run: |
#           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag fabianaribas/trabalho-individual-2020-1:client_latest

#       - name: Docker Push
#         run: docker push fabianaribas/trabalho-individual-2020-1:client_latest
