name: CI

on:
  push:
  pull_request:
    branches: [ master ]
  deployment:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build api containers
        run: docker-compose up --build -d
        
  tests:
    needs: [ build ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
      
    - name: Build api container
      run:  |
        docker-compose up --detach --build db api
        
    - name: Run api tests
      run: |
        docker-compose run -e "RAILS_ENV=test" api rake test
        
    - name: Build client container
      run: |
        docker-compose up --detach --build client
        
    - name: Run client tests
      run: |
        docker-compose run client yarn run test:unit
        
    - name: Sonar coverage

    
    
